### PR TITLE
Fixed a couple issues and made some changes to api (command line)

### PR DESCRIPTION
**Pull request by silasbur**
I fixed the issues, changed arguments, added a dockerfile, etc

### CODE REVIEW

**Comment by brantsch** [comment]
Thank you for your pull request - I'm very happy about use of and interest in this tool! I'll review the changes and hopefully merge them within the next few days. As life happens, I haven't recently needed this software myself for some time, so my knowledge of it is not very current.

Why did you include a Dockerfile? I appreciate the move, but haven't thought (yet) that this tiny script warrants a Docker container.

**Comment by silasbur** [comment]
I included a Dockerfile because I was interested in using Docker since I hadn't used it before, and because I wasn't sure of the best way to run the script remotely for free. I was able to set up a free tier GCE (google product) VM  and run the container on that. Since setting that up I have realized that using Lambda Functions (amazon product), or Cloud Functions (google product) may be a better fit. Please tell me if you have any suggestions.

**Comment by n14s** [comment]
Hey Silas,
I'm tried out your Fork, but I'm getting 404 responses.

```
py wg-gesucht-updater.py -p mypassword -u mymail@mail.de -a 96xxxxx -w 180
INFO:root:deactivate
INFO:root:96xxxxx
INFO:root:<Response [404]>
INFO:root:activate
INFO:root:96xxxxx
INFO:root:<Response [404]>
```

Did you ever face this issue?
Is your fork working for you right now?

**Comment by silasbur** [comment]
It is working for me...

**Pull request closed without merging**
